// <auto-generated />
namespace Muscle_App_.NetFrameworks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenameColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202410141345318_RenameColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
